[package]
name = "abis"
version = "1.0.0"
rust-version = "1.73"
edition = "2021"

[lib]
name = "abis"

[dependencies]
lazy_static = "1.4.0"
alloy-json-abi = "0.4.2"
serde_json = "1.0.108"
alloy-primitives = "0.4.2"
